version: '3.8'

services:
  shard1:
    build: .
    env_file:
      - config/.env.qa
    environment:
      - CI=true
      - TEST_ENV=qa # the "env" chip in the reportingLabs header
    volumes:
      - ./reports-shard1:/app/reports/html-report
      - ./allure-shard1:/app/allure-results
      - ./blob-shard1:/app/blob-report
      - ./rl-shard1:/app/reporting-labs # reportingLabs: index.html, report.pdf, report.json
    command: npx playwright test --project=chromium --shard=1/4

  shard2:
    build: .
    env_file:
      - config/.env.qa
    environment:
      - CI=true
      - TEST_ENV=qa # the "env" chip in the reportingLabs header
    volumes:
      - ./reports-shard2:/app/reports/html-report
      - ./allure-shard2:/app/allure-results
      - ./blob-shard2:/app/blob-report
      - ./rl-shard2:/app/reporting-labs # reportingLabs: index.html, report.pdf, report.json
    command: npx playwright test --project=chromium --shard=2/4

  shard3:
    build: .
    env_file:
      - config/.env.qa
    environment:
      - CI=true
      - TEST_ENV=qa # the "env" chip in the reportingLabs header
    volumes:
      - ./reports-shard3:/app/reports/html-report
      - ./allure-shard3:/app/allure-results
      - ./blob-shard3:/app/blob-report
      - ./rl-shard3:/app/reporting-labs # reportingLabs: index.html, report.pdf, report.json
    command: npx playwright test --project=chromium --shard=3/4

  shard4:
    build: .
    env_file:
      - config/.env.qa
    environment:
      - CI=true
      - TEST_ENV=qa # the "env" chip in the reportingLabs header
    volumes:
      - ./reports-shard4:/app/reports/html-report
      - ./allure-shard4:/app/allure-results
      - ./blob-shard4:/app/blob-report
      - ./rl-shard4:/app/reporting-labs # reportingLabs: index.html, report.pdf, report.json
    command: npx playwright test --project=chromium --shard=4/4